### ISSUE TITLE
Routing with parameters

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic-plugin-deeplinks#10]
Hi,

I just replaced cordova-plugin-customurl with this plugin as I believe has much better integration with ionic2.
I cannot find an example or figure out how you handle url params. 
For instance if I have a route `/activate/12345` works great if I do 
```
{ 'activate/:token': ActivationPage }
```
and on ActivationPage I do 
```
this._navParams.get('token');
``` 

But if I have a route like `/activate?token=12345` how can this work?
From the code I understand a route declaration like `/activate` will not match a link like `/activate?token` since you are not removing the params before matching the route. Also a declaration of `/activate?token` will not match either. Am I missing sth?

**Comment by mlynch** [comment]
Thanks,  I see the issue, will hopefully have a fix today

**Comment by mlynch** [comment]
Fixed!
