### ISSUE TITLE
[Cordova 7.0.0] Cannot find module '../plugman/platforms/ios'

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-plugin-deeplinks#100]
Hi,

After my upgrade to Cordova 7.0.0 and update of all my plugins, I wasn't able to remove and add the iOS platform (ionic rm/add platform ios). I was facing the following error:

     Error: Cannot find module '../plugman/platforms/ios'

I removed then the ionic-plugin-deeplinks plugin (ionic plugin rm ionic-plugin-deeplinks) and I was then successfully able to achieve these operations.

Note: Once the iOS platform was successfully added, I was then able to add the ionic-plugin-deeplinks plugin again.

Summarized:

     ionic plugin add ionic-plugin-deeplink
     ionic platform rm ios
     ionic platform add ios

=> Error: Cannot find module '../plugman/platforms/ios'

     ionic plugin rm ionic-plugin-deeplink
     ionic platform rm ios
     ionic platform add ios
     ionic plugin add ionic-plugin-deeplink

=> ok

**Comment by peterpeterparker** [comment]
Sorry for the duplicate of https://github.com/driftyco/ionic-plugin-deeplinks/issues/99

**Comment by Prodev2017** [comment]
where is  ionic plugin add ionic-plugin-deeplink?

**Comment by kierandesmond** [comment]
Was tehre a fix found here? Still have this bug too.

**Comment by Prodev2017** [comment]
I didnt fix it yet

**Comment by zjbennett** [comment]
Any update on this I'm having the same issue. Seems to be stopping the Deeplink from working altogether?
