### ISSUE TITLE
Enabling automatic url verification for Android

### ISSUE THREAD

**Issue by mvidailhet** [driftyco/ionic-plugin-deeplinks#12]
As specified in the [documentation](https://developer.android.com/training/app-links/index.html#config-verify), it would be nice to enable automatic url verification for Android apps.

If I understand correctly, the app would be considered automatically as the default one to open the specified url on devices having Android 6.0 or more.

**Comment by ihadeed** [comment]
I'm running on Android 5 and the host I defined got recognized right away. ( I can only use the HTTPS url, can't use URL SCHEME on this version of Android)

**Comment by masimakopoulos** [comment]
I believe the `android:autoVerify="true"` is missing from the generated intend.
