### ISSUE TITLE
Argument in deeplink is being truncated

### ISSUE THREAD

**Issue by morris014** [driftyco/ionic-plugin-deeplinks#13]

**Comment by mlynch** [comment]
Do you have any more info on this at all? I need *something* to go on 😆

**Comment by ihadeed** [comment]
Here @mlynch , I have the same issue. Here's the console log:
![image](https://cloud.githubusercontent.com/assets/13794420/16999030/fef7ee14-4e89-11e6-8622-377d8823de1e.png)

The last character is getting removed from the link for some reason. I'll have a look at the source code and see.

**Comment by ihadeed** [comment]
I think I figured out, gonna submit a PR now. Here's a playground: https://jsbin.com/dubewowiba/edit?js,console

**Comment by mlynch** [comment]
Pushed a new release w/ that PR, 1.0.9
