### ISSUE TITLE
phonegap cloud build - support

### ISSUE THREAD

**Issue by kbalaguru** [driftyco/ionic-plugin-deeplinks#15]
How to declare these parameters in [phonegap build](https://build.phonegap.com/) config.xml file 
URL_SCHEME=myapp 
DEEPLINK_SCHEME=https 
DEEPLINK_HOST=example.com

Tried like below 
`<plugin name="ionic-plugin-deeplinks" source="npm">
			<param name="URL_SCHEME" value="myapp" />
			<param name="DEEPLINK_SCHEME" value="http" />
			<param name="DEEPLINK_HOST" value="mysite.com" />
</plugin>`

But getting parameters missing error.

**Comment by mlynch** [comment]
Hey, not sure. The preferences are for the platforms specifically, so you'll find the values inside of `platforms/android/AndroidManifest.xml`, and the plist file for ios.

**Comment by leoruhland** [comment]
I know it is already closed and possibly already resolved, but only to inform that it works pass the parameters, but they must be inside a <params> tag:

```
<plugin name="ionic-plugin-deeplinks" spec="1.0.14">
    <params>
        <param name="URL_SCHEME" value="myapp" />
        <param name="DEEPLINK_SCHEME" value="https" />
        <param name="DEEPLINK_HOST" value="mysite.com" />
    </params>
</plugin>
```
