### ISSUE TITLE
Deep linking is not working

### ISSUE THREAD

**Issue by neosekar** [driftyco/ionic-plugin-deeplinks#16]
Deep linking works in whatsapp, hangouts, mail. 
But in **Facebook in android** , the links gives the **400 error** and the app is not opening 
And also the **twitter in IOS** , the links gives the **404 error** and the app is not opening. 

Could you please help me in this and thank in advance for helping !

**Comment by vasanthns** [comment]
Hi,

We are trying to open the app and navigate to a particular page (using the route match). Exact same code works on other apps, but Facebook in Android and Twitter in iOS is not launching the app at all.

regards,
Vasanth

**Comment by mlynch** [comment]
Not sure this is an issue with this plugin, if it's working elsewhere. Could be Facebook or Twitter being rude

**Comment by kodeine** [comment]
@mlynch Deeplinks work via whatsapp and regular android browser but not via facebook or chrome browser. Please reopen this.
