### ISSUE TITLE
SPA links (using #) do not parse arguments in Android

### ISSUE THREAD

**Issue by masimakopoulos** [driftyco/ionic-plugin-deeplinks#18]
I have a link like `http://www.example.com/#/activate?token=1234&id=55`.
The plugin triggers a deep link fine and matches a route definition like `/#/activate` but the args object is empty. 
Java considers everything after # as the fragment part of the Uri and not part of the query string. In the matched object, queryString is undefined and fragment is "/activate?token=1234&id=55"

Opening the same exact url without the has and its following slash works fine btw.

**Comment by mlynch** [comment]
Thanks, I see the issue. Working on a fix now...

**Comment by mlynch** [comment]
Hey, can you try again on master? Just pushed a fix for this...

Make sure you don't put the hash in the path to match. Now it treats hash and non-hashed paths as the same for the route matching

**Comment by mlynch** [comment]
Assuming fixed for now
