### ISSUE TITLE
Installation step error

### ISSUE THREAD

**Issue by yahyazini** [driftyco/ionic-plugin-deeplinks#2]
I tried using the installation step from the readme file but it's missing:
* the character "=" after URL_SCHEME
* --variable before DEEPLINK_HOST

Which returns the following errors:
`Error: invalid variable format: URL_SCHEME`
`Error: Variable(s) missing (use: --variable DEEPLINK_HOST=value).`

The correct format is:
`cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=myapp  --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=example.com
`

**Comment by mlynch** [comment]
Good catch, thanks!

**Comment by bodronRamona** [comment]
Nice one! Ty!
