### ISSUE TITLE
deeplinking to URL not working properly when app is in foreground (inactive state)

### ISSUE THREAD

**Issue by baion** [driftyco/ionic-plugin-deeplinks#20]
I am using ionic-plugin-deeplinks for deeplinking, deeplink works properly when app is in background . But it fails to route when the app is foreground and inactive. My code structure is same as example shared on the plugin.

$ionicPlatform.ready(function() {
// Note: route's first argument can take any kind of object as its data,
// and will send along the matching object if the route matches the deeplink
$cordovaDeeplinks.route({

}).subscribe(function(match) {

}, function(nomatch) {

** i am using $location.path(loc) for the navigation . As i have few dynamic params on the url .

When app is in background , deeplinking works absolutey fine. Whereas when the app is inactive but running on forground( when user has switched to some other app), clicking on any url open the app but doesn't route to the particular page.

2) Can i add an event , like universal-links plugin does and listen to the event for routing .

<universal-links>
    <host name="example.com" scheme="https" event="ul_myExampleEvent" />
</universal-links>

**Comment by mlynch** [comment]
So I understand, do you mean when the app is completely closed and stopped it works fine, but when it's "running" but not active it doesn't route properly?

**Comment by baion** [comment]
Yes.
For an example , when i switch from my app to gmail and click an url - It doesn't route . 

Whereas , if i'll close my app , and clicks on an url from other app , my app opens and routes to the particular path.

**Comment by mlynch** [comment]
Thanks. Did you add any console logs to the subscribe callback to see if it was logging anything?

**Comment by baion** [comment]
yes , well let me share the full info:
1) I have installed the plugin as below:
sudo cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=<url-sheme> --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=<hostname> --variable ANDROID_PATH_PREFIX=/static/index.html 
my application url is "https://www.xyz.com/static/index.html#/home/item/t95"

I have set ANDROID_PATH_PREFIX as /static/index.html  since we can't escape # , and the uri pattern match will not match(Please correct me if i am wrong). 

On device ready ,  i have following blocks 
                $cordovaDeeplinks.route({
                  '#/home/item': {
                    target: 'item',
                    parent: 'home'
                  }
                }).subscribe(function(match) {
               }, function(nomatch) {

When i click on a link- app is background , it always goes to the nomatch, hence to proceed i use 
$location.path(nomatch.$link.fragment) 
So it routes to the page properly.
I have same code inside "onResume" block as well.
Now when i switch an app(gmail) , and clicks a link , the "nomatch" inside onResume  again triggers, and calls $location.path(nomatch.$link.fragment), but doesn't navigates to the page.

Surprisingly , the subscribe call back messages printed before the onResume() messages.

**Comment by mlynch** [comment]
Try pulling master, and then remove the hash from your path and try again. I'm not able to reproduce this, it's working fine for me...
