### ISSUE TITLE
2 Questions regarding the plugin behavior

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic-plugin-deeplinks#22]
Hi all

1. I have notice that the plugin trims the first path of the url why?
When trying to use the next url to open the app:
`myapp://reset/:token` I have notice that the match will be for the `:token` only
or another example `myapp://reset/pass/:token` the match will be for `/pass/:token` why the first part is being removed?

2. also I cannot open the app with the `DEEPLINK_HOST` When im going to my phone browser and type in `https://myapp.com/reset` nothing happens.. do I miss something?

**Comment by mlynch** [comment]
@royipressburger when using the custom URL scheme format, if you pass any additional path items the first portion is treated as the host. This is how the URL parsing libraries on ios work, and to keep with URL standards, we recommend either not using path params for custom URL schemes, or using a filler host like `myapp://app/reset/:token`.

As for the second part, make sure you've configured all the necessary deeplinking stuff on the iOS or Android side, it's kind of a pain

**Comment by royipressburger** [comment]
@mlynch thanks for the fast response... regarding the second part.. what else i neex to configure? I do not see anything on the readme but the plugin installation

**Comment by mlynch** [comment]
https://github.com/driftyco/ionic-plugin-deeplinks#ios-configuration
