### ISSUE TITLE
Deeplinks.routeWithNavController Cause exception with ionic serve

### ISSUE THREAD

**Issue by royipressburger** [driftyco/ionic-plugin-deeplinks#23]
Hi

When running `ionic serve --lab` 
the function Deeplinks.routeWithNavController causes:
```js
browser_adapter.js:77 Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to object
    at resolvePromise (zone.js:538)
    at zone.js:574
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (ng_zone_impl.js:37)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:426)
```

any ideas?

ionic info:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.4 LTS 
Node Version: v5.9.0

**Comment by mlynch** [comment]
How are you getting the reference to the nav controller object?

**Comment by royipressburger** [comment]
@mlynch like that: `  @ViewChild(Nav) navChild:Nav;`

**Comment by mlynch** [comment]
I'd need to see more code to know exactly

**Comment by royipressburger** [comment]
```js
  public rootPage: any;
  @ViewChild(Nav) content: Nav;

  constructor(platform: Platform, error: HttpErrorHandler, geos: GeosService) {
    // TODO: Not a good idea!
    platform.ready().then(() => {
      geos.load().subscribe(() => this.rootPage = AuthTracker);
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
      // StatusBar.backgroundColorByName('red');
      Splashscreen.hide();
      // Convenience to route with a given nav
      Deeplinks.routeWithNavController(this.content, {
        '/reset/:token': ResetPasswordPage
      }).subscribe((match) => {
        console.log('Successfully routed', match);
      }, (nomatch) => {
        console.warn('Unmatched Route', Object.keys(nomatch.$link)[3]);

        console.warn('Unmatched Route', nomatch.$link.url);
        console.warn('Unmatched Route', nomatch.$link.path);
        console.warn('Unmatched Route', nomatch.$link.schema);
      });
    });
  }
```

This is my code in `app.ts`, when running like this on `ionic serve` i get the error above.
but when commenting out the deeplink I get no errors

**Comment by royipressburger** [comment]
@mlynch any ideas?

**Comment by mlynch** [comment]
Instead of doing it in the constructor, try doing it in the `ngOnAfterViewInit` lifecycle event:

https://github.com/driftyco/ionic2-deeplinks-demo/blob/master/app/app.ts#L26

**Comment by royipressburger** [comment]
@mlynch I still have this issue.. even when the `Deeplinks.routeWithNavController` is under `ngAfterViewInit`

**Comment by mlynch** [comment]
I don't know what's going on here, if you had a project I could test that would help. What odes your template look like?

**Comment by mlynch** [comment]
Also is your this.content resolving in the `ngAfterViewInit` if you inspect or console log it?

**Comment by royipressburger** [comment]
@mlynch Hi again :)

First of all you can clone this example https://github.com/royipressburger/navControll-error-example
Run `ionic serve --lab` and you will be able to reproduce the problem

Also I'm able to inspect it. Want me to look on specific property?

**Comment by mlynch** [comment]
Thanks, hugely helpful. I'm taking a look now...

**Comment by mlynch** [comment]
Okay, a few things. First, you have three callback functions, try removing the last one. I installed the plugin and then tested your app and it's working great for me. Let me know if that doesn't work and I'll reopen.

**Comment by royipressburger** [comment]
Hi again @mlynch sorry for the late response.. This was actually a problem with how I used `console.warn` on the `nomatch`
Looks like when running in the browser the plugin gets 
`cordova_not_available` as the `nomatch` route.. 

so `nomatch.$link` is undefined :)

Thanks again for your help
