### ISSUE TITLE
firebase dynamic links?

### ISSUE THREAD

**Issue by kodeine** [driftyco/ionic-plugin-deeplinks#26]
So if i want to use [Firebase Dynamic Links](https://firebase.google.com/docs/dynamic-links/) do i have to use along with this package?

**Comment by mlynch** [comment]
Not sure, I don't know how that product works. If it does any auto navigation for you that won't work with Ionic. However, you could add their code to detect the link and navigate on your own.

I have no plans to support Dynamic Links, so those are the options I think
