### ISSUE TITLE
Question - Universal Link in email

### ISSUE THREAD

**Issue by DigitalMystery** [driftyco/ionic-plugin-deeplinks#27]
Is there something unique I need to do to have the universal link work from an email?  I have the link working when clicking from my website so everything appears to be set up correctly.   I am using Send Grid on my server to send emails and I have turned click tracking off.  When I click the link in my email I get "Safari cannot open the page because the address is invalid".

**Comment by mlynch** [comment]
What does the link look like? If it's an invalid address, that might be the issue

**Comment by DigitalMystery** [comment]
data-saferedirecturl="myApp://myLocation"

With only the data-saferedirecturl in the email I at least get it to open safari which returns the error.  If I add an href with the same location as above nothing happens.  Do I need to actually call a page on my website instead of using the above?

**Comment by DigitalMystery** [comment]
So I added the Android version just a couple of minutes ago and now I am confused.....  I have the Android version working from the website.  I also have the android version opening from an email as long as it was sent to my Hotmail.  Gmail does nothing.  If i look at the link in hotmail it looks correct.  When i forward the email to Gmail I do not see the data-saferedirecturl at all.

**Comment by DigitalMystery** [comment]
I read that gmail does not support universal links so I suppose that resolves this as a non-issue.
