### ISSUE TITLE
Version 1.0.10 

### ISSUE THREAD

**Issue by AdrianMarinica** [driftyco/ionic-plugin-deeplinks#28]
I am using the plugin in PhoneGap Build and the latest NPM version (1.0.9) crashes the build. The log files indicate 3 errors in the lines removed by the latest commit (394f3f43bdaef9af58b88ae03644a915ae1adbad). Can you bump the version up by one in NPM also, so that package uses the codebase with the latest commit? This way we should be able to use the plugin in PhoneGap Build. Currently we are using 1.0.4, as that is the version before the issues were introduced. Thanks!

**Comment by mlynch** [comment]
Try now, just pushed 1.0.10 to npm 🍻

**Comment by AdrianMarinica** [comment]
Thanks for the quick response. It works now!
