### ISSUE TITLE
Deeplinks.routeWithNavController breaks my navigation logic.

### ISSUE THREAD

**Issue by Natanael1234** [driftyco/ionic-plugin-deeplinks#29]
I'm developing an app using Ionic 2. 

The router pushes an page into my navcontroller. It creates an navigation history and an back arrow button in my navbar. But I wish my navigation is made just setting rootPage.

How could I control the navigation so that it sets the rootPage instead pushes another page?

**Comment by twicejr** [comment]
Pass the page name and the navParams as JSON. This is what I'm using right now:

Deeplinks.route({
            '/:page/:navParams': 1 //1, because it doesnt matter.
        }).subscribe((match) => {
            var navParams:any = null;
            if (typeof match.$args.navParams != 'undefined') {
                navParams = JSON.parse(decodeURIComponent(match.$args.navParams));
            }
            //get the page object by name is a function you should create. openPage is to be replaced by your own router function
            this.openPage(this.getPageObjectByName(match.$args.page), navParams);

**Comment by mlynch** [comment]
Yep just use the vanilla `route` function which you can completely control. I'll look into setting root as an option

**Comment by mlynch** [comment]
@twicejr just added a feature where you can pass `root: true` as an option and it'll set the root instead of navigating:

```javascript
Deeplinks.routeWithNavController(this.nav, {
  // routes
}, {
  root: true
}, (match) => {}, (nomatch) => {});
```

The options is optional

**Comment by pantonis** [comment]
Regarding the new options. Cannot find it in the d.ts file

I have:

static routeWithNavController(navController: any, paths: any): Observable<DeeplinkMatch>;
