### ISSUE TITLE
Got a deeplink that didn't match – {$link: Object}

### ISSUE THREAD

**Issue by tmvnk** [driftyco/ionic-plugin-deeplinks#30]
When I try testapp://profile/:uid I never achieve a match..

testapp://profile is working

Is this a issue or my mistake?

Best Tom

**Comment by mlynch** [comment]
@tmvnk can you share your route config?

**Comment by mlynch** [comment]
Closing due to lack of response and lack of reproducible test case. Let me know if you have something and I'd be happy to dig in 🍜
