### ISSUE TITLE
iTunes rejection due to excessive using of ASIdentifierManager

### ISSUE THREAD

**Issue by bushev** [driftyco/ionic-plugin-deeplinks#31]
Hello!

I'm trying to submit my app to the AppStore and got rejection with the following reason:

> We found that your app uses the Advertising Identifier but does not include ad functionality. This does not comply with the terms of the Apple Developer Program License Agreement, as required by the App Store Review Guidelines.

I'm not using any ads in my app and Apple support wants me to remove any usage of:

> If your app does not serve ads, please check your code - including any third-party libraries - to remove any instances of:
> 
> class: **ASIdentifierManager**
> selector: **advertisingIdentifier**
> framework: **AdSupport.framework**

**Comment by mlynch** [comment]
Hey sorry about this. I had pushed a fix last week in the latest release that didn't bind to the advertising identifier. Can you try the most recent release and see if that fixes it?

**Comment by bushev** [comment]
@mlynch Hi! Great, I will!

**Comment by bushev** [comment]
Looks like it works, thanks! 👍

**Comment by mlynch** [comment]
🍻
