### ISSUE TITLE
Support multiple domains

### ISSUE THREAD

**Issue by Ti-webdev** [driftyco/ionic-plugin-deeplinks#32]
Using [cordova-universal-links-plugin](https://github.com/nordnet/cordova-universal-links-plugin) I can define more than one host:

``` xml
<host name="site1.com" scheme="https" />
<host name="site2.net" scheme="https" />
<host name="site3.io" scheme="https" />
```

It is possible with ionic-plugin-deeplinks?

**Comment by smason** [comment]
just started to look at this as well, had kind of been assuming it would just work…

Poking into the source code it looks as though it would be a bit of work to enable.  Not sure if anyone is looking into this, but I'd be interested if they did!

**Comment by tehfonsi** [comment]
It would be nice if it is possible to create something like this:

```
           <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="example" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" />
                <data android:scheme="http" />
                <data android:host="www.example.com" android:pathPrefix="/" />
                <data android:host="example.com" android:pathPrefix="/" />
            </intent-filter>
```

Which works for:

- example://<url>
- https://www.example.com/<url>
- http://example.com/<url>

**Comment by smason** [comment]
Not used `cordova-universal-links-plugin`, but guess their syntax would allow @tehfonsi's (which is similar to what I'd want to do as well (I'm also targeting iOS), i.e:

```
<host scheme="example" />
<host name="www.example.com" scheme="https" path="/" />
<host name="example.com" scheme="https" path="/" />
```

which would work for iOS by ignoring the `path` options as they are specified via the `apple-app-site-association` file, on the webserver and hence away from Ionic.  Might be nice if the app association file could eventually be auto-generated!

**Comment by samarpanB** [comment]
Any update on this ? We are having our own ionic app. We would like to use this plugin for deep linking. But without multiple hosts, this is unusable. Can someone tell when will this be possible ?

**Comment by mlynch** [comment]
I did this the old fashioned way, as I *really* want to avoid shipping a lot of XML parsing code like the universal links plugin does. Now, you can specify up to 5 hosts, by (optionally) setting these variables:

First: `DEEPLINK_SCHEME`, `DEEPLINK_HOST`, and `ANDROID_PATH_PREFIX`
Second: `DEEPLINK_SCHEME_2`, `DEEPLINK_HOST_2`, and `ANDROID_PATH_PREFIX_2`
Third: `DEEPLINK_SCHEME_3`, `DEEPLINK_HOST_3`, and `ANDROID_PATH_PREFIX_3`
Fourth: `DEEPLINK_SCHEME_4`, `DEEPLINK_HOST_4`, and `ANDROID_PATH_PREFIX_4`
Fifth: `DEEPLINK_SCHEME_5`, `DEEPLINK_HOST_5`, and `ANDROID_PATH_PREFIX_5`
