### ISSUE TITLE
URL_SCHEME not update plist on "ionic build ios" only on "ionic platform add ios"

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-plugin-deeplinks#33]
Hi,

First thx for the awesome plugin, works like charm as always!

Not sure that following is a bug but I thought I should report it, you know just in case...

I noticed that, if you change afterwards respectively after the first installation the URL_SCHEME in the config.xml, that change not gonna be applied to the .plist file of the iOS platform if you only build your application (ionic build ios). To apply such a change, you would have to do it manually in your plist file too or to remove and add the platform again (ionic platform rm ios / ionic platform add ios).

As I said, maybe not a bug, but I lost hours trying to open the app with the wrong url :(
If no bug, I probably miss that in the documentation, as I often always do ;)

**Comment by mlynch** [comment]
Thanks, this seems to be a Cordova thing so I'll keep this up but will close as I don't think this is related to the deeplinks plugin specifically.
