### ISSUE TITLE
match.$route undefined

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-plugin-deeplinks#35]
Hi,

When using Deeplinks.route with a route containing a parameter, on success routing, I get an undefined match.$route (match itself is defined but $route is missing).

Here my code in my app.ts:

    ngAfterViewInit() {
        this.platform.ready().then(() => {
            // Convenience to route with a given nav
            Deeplinks.route({
                '/myroute/:myId': MyPage
            }).subscribe((match:DeeplinkMatch) => {

                // ----> Here, match.$route == undefined
                alert('Successfully matched route' + JSON.stringify(match.$route));

            }, (nomatch) => {
                console.error('Got a deeplink that didn\'t match', nomatch);
            });
        });
    }

**Comment by mlynch** [comment]
@peterpeterparker, can you show me more of your code? It's going to return the data you ass into the route, so `MyPage`, which might be undefined?

**Comment by peterpeterparker** [comment]
unfortunately can't show you the code. I had to figure out a solution and changed my code.

but couldn't you reproduce the problem with the example of code I posted above?

**Comment by mlynch** [comment]
I'm going to close as I couldn't reproduce and I suspect it's an issue outside of this plugin. If you have more of an example please let me know.
