### ISSUE TITLE
Unable to reach specific route like myapp://about

### ISSUE THREAD

**Issue by ranvirgorai** [driftyco/ionic-plugin-deeplinks#36]
there i am unable to go specific page, it open the application main page **myapp://**  and if i pass **myapp://about** the it also start first page only. so how can go to specific  state using deep link. like **myapp://about**, **myapp://menu** etc

**Comment by mlynch** [comment]
You mean in an <a href? The system is meant for the initial load not subsequent navigations. 

Something I could consider down the road but for now I'd rather have the framework solve navigation in the app itself.
