### ISSUE TITLE
Doesn't save properly in package.json

### ISSUE THREAD

**Issue by danielcrk-cn** [driftyco/ionic-plugin-deeplinks#37]
When the plugin is installed (cordova plugin add... --save) it is saved to the package.json, but with none of the variables, so if you delete the platforms folder and try to build it again, it ends with the error "`Failed to install 'ionic-plugin-deeplinks':Error: Variable(s) missing: URL_SCHEME, DEEPLINK_SCHEME, DEEPLINK_HOST`".

Is there a way to save all the variables as well?

I tried using this syntax, but no go:
```
{
      "variables": {
        "URL_SCHEME": "*****",
        "DEEPLINK_SCHEME": "https",
        "DEEPLINK_HOST": "*****.se"
      },
      "locator": "ionic-plugin-deeplinks",
      "id": "ionic-plugin-deeplinks"
}
```

**Comment by mlynch** [comment]
It appears that Cordova handles this by saving them into `config.xml` for loading later. That should Just Work. Closing as this is a Cordova question anyways.
