### ISSUE TITLE
Error: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by tyvdh** [driftyco/ionic-plugin-deeplinks#40]
Recently started getting this error. Likely due to a Node upgrade.
I'm running node `v6.6.0` and npm `3.10.6`

```
Running command: "/Users/Tyler/Desktop/Web/Tiny Bank/tiny-bank-ionic/hooks/after_prepare/010_add_platform_class.js" "/Users/Tyler/Desktop/Web/Tiny Bank/tiny-bank-ionic"
add to body class: platform-ios
Error: Cannot read property 'forEach' of undefined
```

**Comment by mlynch** [comment]
Ah, and this looks related to the hooks we added, will check...

**Comment by mlynch** [comment]
@tyvdh when do you get this error (after running which command?)

**Comment by syndesis** [comment]
I get it after running 'ionic prepare' on both android and ios

**Comment by mlynch** [comment]
I just reverted PR #21 and published a new version of the plugin. Can you try and see if that works?

**Comment by syndesis** [comment]
Yes, that fixed it for me. Thanks!

**Comment by mlynch** [comment]
Cool, will close for now, thanks.

**Comment by tyvdh** [comment]
@mlynch Works for me too. Thanks!
