### ISSUE TITLE
Deep link fails to launch app and link: iOS 9/10 WKWebView + Ionic 1.5

### ISSUE THREAD

**Issue by argyleink** [driftyco/ionic-plugin-deeplinks#47]
Deep links with this plugin are working great **if the target app is already open.** If the app is closed (no task in the OS), and the deep link is fired, iOS opens the app to a blank webview, which loads no html, css, js. Safari remote inspector shows the below error:

![screen shot 2016-10-10 at 11 00 56 am](https://cloud.githubusercontent.com/assets/1134620/19279895/2481c37c-8f98-11e6-82de-864c31152936.png)

Furthermore, from the remote inspect console, the `window.location.href` says "about:blank"

The plugin doesn't seem to be gracefully handling the cold launch scenario for a deep link. 

Our iOS setup is using WKWebView with the default localhost settings to point to our webview ionic app logic. I feel like this bug is not in our code, and must be something in the native proxy code between the deep link and the ionic client code.

Let me know if I can share any more repro steps or environment attributes to help.

**Comment by mlynch** [comment]
Hey, seeing this now. Will try to get to this tomorrow

**Comment by mlynch** [comment]
Okay, just tested this in an iOS 10 simulator and the app did boot on a cold boot for the custom URL scheme urls. Are you doing a universal link or a custom URL scheme link?

**Comment by mlynch** [comment]
Also, I wonder if this has anything to do with WKWebView...

**Comment by mlynch** [comment]
Just tested this on iOS 10 device with universal links as well as WKWebView and it's all working for me...

Any chance one of you could bundle up an app into a zip file and email me? max@ionic.io

Or give me more info on how you are linking/etc. so I can dig in a bit

**Comment by argyleink** [comment]
yep, I'll gather some stuff tomorrow for you. maybe even make a new ionic app and try the plugin on a fresh app to verify. thanks for diggin in, I'll report back with results.

**Comment by argyleink** [comment]
whelp, confirmed that cold boot deep link works in a blank ionic 1 starter. so it must be our stack of cordova plugins that are getting in the way somewhere.. we're not comfy sending you the bits yet, but maybe down the road. thanks, i'll close this for now until i have stronger repro steps.

**Comment by mlynch** [comment]
No worries, feel free to email me whenever. As for plugins, make sure you don't have multiple ones for custom URL schemes/deeplinking/etc. (like branch metrics) as that could get in the way.

**Comment by argyleink** [comment]
Well, i'm still hacking on this. From XCode I can see that the `handleLink` function is firing before `onDeepLink` has had a chance to register a callback. So no handlers are present for the deep link when handleLink tries to do it's job. 

Our app is pretty big, and that's the best factor I can think of here that's significantly different from the slim/minimal app we built to verify cold boot deep links work as expected. I think our app takes a while to parse all the js, and in that time, the native code has done it's job, not giving our app time to register a callback to handle the deep link passed data. 

Have any ideas on how I can work around our slow app? Or ways to slow down the plugin handleLink function?

**Comment by argyleink** [comment]
looks like this may be a known cordova issue. see here https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/93

the good news: there's a workaround in that plugin, but registering a window function and using timeouts.
the bad news: this plugin uses registered callbacks, so a window function trick wont have access to $state and other ionic/angular injected deps.

thoughts?

**Comment by argyleink** [comment]
BUT! you're plugin does work on cold boot, sooooooooo, you dont need no stinkin workaround ;)

**Comment by mlynch** [comment]
I'm beginning to suspect WKWebView. Perhaps Cordova's bus for it is acting in a different manner?

**Comment by argyleink** [comment]
You were correct. Switching to https://github.com/driftyco/cordova-plugin-wkwebview-engine as our WKWebView plugin resolves the cold boot bug! Trust those hunches mang!
