### ISSUE TITLE
Use Deeplink in browser

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic-plugin-deeplinks#5]
Is it possible to use Deeplinks in the browser (in an ionic v2 app, throught ionic serve)?

When I try, the console outputs the following error:

`Native: tried calling Deeplinks.routeWithNavController, but Cordova is not available`

Ionic info:

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.23
Ionic App Lib Version: 2.0.0-beta.13
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
Node Version: v5.7.0

**Comment by mlynch** [comment]
Not currently, no. Ideally it would work though, regardless of how Ionic 2 routing ends up working. I'll see if I can get this in. Thanks!

**Comment by chrisbenseler** [comment]
@mlynch I was trying to use it, as long as Ionic 2 has removed the Router support since beta7 cause Angular 2 does not have a stable version yet.

Thanks for the reply!

**Comment by mlynch** [comment]
Hey @chrisbenseler, just added a preliminary browser target that works somewhat similarly. Mind giving it a try and letting me know what you think?

**Comment by chrisbenseler** [comment]
@mlynch sure!

I updated my ionic 2 project:

_Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9-201606271842
Ionic CLI Version: 2.0.0-beta.33
Ionic App Lib Version: 2.0.0-beta.19
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04.1 LTS 
Node Version: v6.2.2_

ionic-native is
_"ionic-native": "1.3.10"_

I tried to use this code 

```
platform.ready().then(() => {
    
    Deeplinks.routeWithNavController(this.nav,{
      '/login': Login
    }).subscribe((match) => {
      // match.$route - the route we matched, which is the matched entry from the arguments to route()
      // match.$args - the args passed in the link
      // match.$link - the full link data
      console.log('Successfully matched route', match);
    }, (nomatch) => {
      // nomatch.$link - the full link data
      console.error('Got a deeplink that didn\'t match', nomatch);
    });
}
```

and the browser always outputs this:
Got a deeplink that didn't match cordova_not_available

it seems that it won't work within the browser, as long as the cordova is not present for this environment?

**Comment by mlynch** [comment]
Right, for this you'll need to use the cordova browser target. However, we're landing routing/deeplinking into Ionic 2 proper shortly, so you might just want to wait for that...

**Comment by chrisbenseler** [comment]
Sur @mlynch! I'll wait for the new ionic release (beta11 or a release candidate, don't know what is the next step) and then I can test the DeepLink in the browser.

**Comment by kodeine** [comment]
@mlynch should i use this deeplinking package or there's something else coming in ionic2 beta 12 or rc?

**Comment by mlynch** [comment]
There's something coming in either the next or the next next Ionic 2 release. However, this plugin will still be required on the native side to enable things like Universal Links and custom URL scheme support, so they will work in tandem

**Comment by ckmilse** [comment]
Is there some demo?deeplinks

**Comment by ckmilse** [comment]
I'm new ionic2,  i use deeplinks, `Deeplinks.routeWithNavController(this.navChild, {
        '/about-us': AboutPage
      }).subscribe((match) => {
        console.log('Successfully routed', match);
      }, (nomatch) => {
        console.warn('Unmatched Route', nomatch);
      });`
but when i use `history.pushState('', 123,'/about-us');` in browser , the view dosent change `main.js:13115 invalid page component: null`

**Comment by theunreal** [comment]
@mlynch Any updates on this? Seem like it's not implemented yet
