### ISSUE TITLE
Ionic 2: possible to use in the browser environment?

### ISSUE THREAD

**Issue by chrisbenseler** [driftyco/ionic-plugin-deeplinks#55]
I'm trying to use DeepLinks in an Ionic 2 app, in the browser (running via ionic serve) but cordova seems to be required:

plugin.js:33 Native: tried calling Deeplinks.route, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator

Importing from ionic-native
import { Deeplinks } from 'ionic-native';

Is it possible to run in the browser, or only in a device/emulator?

**Comment by promentol** [comment]
I have the same question, it will be pretty useful feature for Progressive Web Apps!

**Comment by mlynch** [comment]
Right now it relies on Cordova, for PWA's we have our DeepLinker, have you tried that? http://ionicframework.com/docs/v2/api/navigation/DeepLinker/

**Comment by promentol** [comment]
Thank you Max, one more question
DeepLinker is using hashtag for routing, are there any configuration to use HTML5 history API
For old ionic v1, inside ui-router we had `$locationProvider.html5Mode(true)` method, are there any alternative for DeepLinker?
