### ISSUE TITLE
Needed for 'Normal' Web Browser?

### ISSUE THREAD

**Issue by queejie** [driftyco/ionic-plugin-deeplinks#58]
If an app is intended only to be used with an apache server to support conventional web browsing, is this plugin needed?  I am able to get URLs to show, but manually entered URLs don't work, with ionic 2.  I'm wondering if that is because I still need to install this plugin.

**Comment by masimplo** [comment]
If I understand correctly your use case, I believe what you need is [DeepLinker](http://ionicframework.com/docs/v2/api/navigation/DeepLinker/) from ionic2 core. Take a look

**Comment by queejie** [comment]
Believe me, I have.  I have worked with it for days to get to the state I described above.

**Comment by mlynch** [comment]
@queejie I'm going to close since the deeplinker plugin here shouldn't be necessary for you.

However, I'd love to hear more about your use of DeepLinker in v2 and what you're having trouble with. Can you share more info (either here or email me max@ionic.io)? We'll get you patched up :)
