### ISSUE TITLE
Cordova plugin rm/add and still get version 1.0.8

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic-plugin-deeplinks#60]
Hey,

I removed and added the ionic-plugin-deeplinks plugin to upgrade to the last version 1.0.12 but I still get 1.0.8. Did I miss something or ?

     cordova plugin rm ionic-plugin-deeplinks --save
     cordova plugin add ionic-plugin-deeplinks --variable U... --save

Running cordova-check-plugins

    plugin: ionic-plugin-deeplinks
    source: npm://ionic-plugin-deeplinks@~1.0.8
    installed version: 1.0.8
    remote version: 1.0.12

Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.0.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by FdezRomero** [comment]
I sent the PR #49 to fix this but has not been merged yet. The plugin DOES get updated, it just shows the wrong version 😉

**Comment by mlynch** [comment]
Landed in bc16fccbb802bcd764e880b7e6e42ca44bf12573
