### ISSUE TITLE
Multiple hosts variables are not optional

### ISSUE THREAD

**Issue by walaman** [driftyco/ionic-plugin-deeplinks#61]
Looks like plugin install failed after latest update https://github.com/driftyco/ionic-plugin-deeplinks/commit/78602eeacbe005710c314a6979fcaf759a426142 

I'm using cordova 6.4.0
With error:

```
Fetching plugin "https://github.com/driftyco/ionic-plugin-deeplinks.git" via git clone
Repository "https://github.com/driftyco/ionic-plugin-deeplinks.git" checked out to git ref "master".
Error: Variable(s) missing (use: --variable DEEPLINK_SCHEME_2=value --variable DEEPLINK_HOST_2=value --variable DEEPLINK_SCHEME_3=value --variable DEEPLINK_HOST_3=value --variable DEEPLINK_SCHEME_4=value --variable DEEPLINK_HOST_4=value --variable DEEPLINK_SCHEME_5=value --variable DEEPLINK_HOST_5=value).
```

I'm using the version https://github.com/driftyco/ionic-plugin-deeplinks/commit/963edcf91e6655a7f63351d40c1a3572e8cc5dd4 now which is fine.

Is it related to some variables with default value `<preference name="..." default="" />` https://github.com/driftyco/ionic-plugin-deeplinks/blob/master/plugin.xml#L16 were unable to be optional?

Thanks.

**Comment by mlynch** [comment]
Ah thanks will check in the morn

**Comment by DigitalMystery** [comment]
Same here, but I am on the nightly build of Cordova.  I just went back to what I was on which was 1.0.8 for now.

**Comment by mlynch** [comment]
Patched it right up 💉
