### ISSUE TITLE
What is the latest version for Ionic 1

### ISSUE THREAD

**Issue by almothafar** [driftyco/ionic-plugin-deeplinks#68]
Hi, 

I know this is easy to just remove and add plugin again to get the latest version, but I read on the home page the new version 1.0.13 has multiple schemes and hosts, I tried to re-add my plugin the latest version was 1.0.8, so I was wondering how to know the latest version available? I usually refer to "releases" tab in Github, but here I see you are not releasing anything nor have any notes for what fixed or added.

I would like to know where you publish releases or suggest to create a release in Github to know the releases, and if you provide changes in each release will be awesome.

Second, I'm really looking for version 1.0.13 for now, any chance to get it soon for it for Ionic 1?

**Comment by mlynch** [comment]
Try 1.0.14 that I just pushed. You had the latest version but the plugin.xml was showing the wrong version.
