### ISSUE TITLE
Generate X-Code Project Entitlements File

### ISSUE THREAD

**Issue by theaccordance** [driftyco/ionic-plugin-deeplinks#7]
**Feature Request**

One thing that `cordova-universal-links-plugin` would do is generate the Entitlements file for X-Code.  Automating this step removes a manual step that would otherwise be required for deploying to iOS. 

Browsing through `cordova-universal-links-plugin`, it looks like this is the point in their code which generates the [entitlement file](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/afterPrepareHook.js#L71)

It's been quite some time since I've used any cloud-compiler service for cordova projects, but automating this step may be necessary to enable the feature for some projects.  You guys probably have a better idea of that though.

**Comment by mlynch** [comment]
Thanks @theaccordance. My initial reaction to that was confusion and I wasn't crazy about adding such a hook, but I can see the value. Will keep this open as a potential feature in the future.

**Comment by mvidailhet** [comment]
As I'm using a build system to build my apps, I needed the plugin to generate the entitlement file and automatically activate the associated domains (and add the applink form the DEEPLINK_HOST variable) in the Xcode project.

So I tweaked the hooks written in the `cordova-universal-link-plugin` to do this. I just made a PR with the code : https://github.com/driftyco/ionic-plugin-deeplinks/pull/21

Hope you'll like it !

**Comment by georgedrummond** [comment]
👍  on getting this feature in the plugin

**Comment by mlynch** [comment]
Did anyone have thoughts on PR #21 and how it worked for you? Happy to get this in there...

**Comment by nikDemyankov** [comment]
That nice feeling, when your hooks are used in other plugins :)

**Comment by fishgrind** [comment]
easy solution: https://github.com/ionic-team/ionic-plugin-deeplinks/issues/162
