### ISSUE TITLE
Path resolves on Android, not on iOS

### ISSUE THREAD

**Issue by Luukschoen** [driftyco/ionic-plugin-deeplinks#8]
First of all, awesome plugin! I'm having trouble finding out why my deeplink does work on Android, but doesn't on iOS. I'm passing an argument which I then resolve inside the app. The args are picked up on Android, but aren't on iOS.

My deeplink looks like this: customscheme://app/nameOfView/?param={paramId} .
On Android this will result in opening the app, with the right args passed and a matched route. On iOS however, it reports to me that the route is unmatched (and I can't see any args passed as well). Do you have any idea on how to solve this? 

in iOS the unmatched route looks like this:
host: "app"
path: "/nameOfView"
queryString: "params=paramID"
scheme: "customScheme"
url: "customScheme://app/nameOfView/?params=paramID"

Thanks for your help in advance!

**Comment by theaccordance** [comment]
Apple discontinued support for deep links with iOS 9.2 in favor of universal links: https://blog.branch.io/ios-9.2-redirection-update-uri-scheme-and-universal-links

**Comment by Luukschoen** [comment]
Yes, I'm aware of that. thanks. I already configured my app and server to use universal links. I can open up the app through an url, but it just fails when i use any params to pass. If I just navigate to other pages inside the app, everything goes fine. If I add a param, it fails to resolve the route

**Comment by Luukschoen** [comment]
I just found out that removing the params part, and only use the paramID fixed it for me.
