### ISSUE TITLE
Support android:pathPrefix

### ISSUE THREAD

**Issue by theaccordance** [driftyco/ionic-plugin-deeplinks#9]
Correct me if I'm wrong, but if I only want certain links to open in-app for Android, I need to specify the `android:pathPrefix` attribute in `AndroidManifest.xml`:

```
<data android:host="foobar.com" android:scheme="https" android:pathPrefix="/public" />
```

Would it be feasible to add support for defining the pathPrefix in the config.xml template? I think so but I'm probably not taking everything into account.

**Comment by mlynch** [comment]
Fixed, available in 1.0.8
